name: release
on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          if echo $version | grep -q -e '-'; then prerelease=-p; fi
          gh release create $version $prerelease \
            -t "Release $version"  \
            -n "See [CHANGELOG.md](./CHANGELOG.md) for details."
